---
title: "dinofun_world"
output: html_document
date: "2022-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(lattice)
```

## Message Frequency by Location/Hours (Sender)

```{r}
proc_data <- function(path) {
  dat <- subset(read.csv(file=path), select = -c(to))
  dat$from <- as.character(dat$from)
  dat$timestamp <- as.POSIXct(dat$timestamp, "%Y-%m-%d %H:%M:%S", tz = "")
  
  return(dat)
}
```

```{r}
# get message frequency by time
fri_combined <- proc_data("../outputs/comm-data-Fri.csv")
sat_combined <- proc_data("../outputs/comm-data-Sat.csv")
sun_combined <- proc_data("../outputs/comm-data-Sun.csv")
```

```{r}
time_slot <- 9
location_filter <- c('Coaster Alley', 'Entry Corridor', 'Kiddie Land', 'Tundra Land', 'Wet Land')

res <- sat_combined %>%
  filter(hour(sat_combined$timestamp) == time_slot & location %in% location_filter) %>%
  group_by(from, location) %>%
  summarise(msg_freq = sum(to_num), .groups = 'keep') %>%
  arrange(desc(msg_freq)) %>%
  head(20)

a <- ggplot(data = res,
                  mapping = aes(x = reorder(from, msg_freq), 
                                y = msg_freq,
                                fill = location)) +
        geom_col() +
        labs(x = "Sender UID", 
             y = "Message Frequency",
             fill = "Location",
             title = "Message Frequency by Sender UID") +
        theme(plot.title = element_text(hjust = 0.5),
              panel.background = element_blank(),
              axis.line = element_line(colour = "black")) + 
        scale_y_log10() +
        coord_flip() +
        geom_text(aes(label = msg_freq), size = 3, hjust = 1.2)
```

```{r}
res_pie <- subset(res, select = -c(from)) %>%
        group_by(location) %>%
        summarise(msg_freq = sum(msg_freq), .groups = 'keep')

b <- ggplot(data = res_pie, 
                  aes(x = "", 
                      y = msg_freq, 
                      fill = location)) +
  geom_bar(aes(fill = location), stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  labs(fill = "Location",
       title = "Message Frequency by Location") + 
  geom_text(aes(label = msg_freq), position = position_stack(vjust = 0.5)) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(hjust = 0.5))

output_plot <- ggarrange(a, b, common.legend = TRUE, legend = "bottom")
      
      annotate_figure(output_plot, top = text_grob("Message Frequency (Sender)",
                                                   face = "bold",
                                                   size = 20))
```

```{r}
res_heat <- fri_combined %>%
  group_by(hour, location) %>%
  mutate(msg_freq = sum(to_num), .groups = 'keep') %>%
  select(hour, location, msg_freq)

ggplot(res_heat, aes(x = as.factor(hour), y = location)) +
  geom_tile(aes(fill = msg_freq)) +
  scale_fill_gradientn(colors = hcl.colors(20, "YlGn")) +
  guides(fill = guide_colourbar(barwidth = 1.5,
                                barheight = 7.5)) +
  coord_equal() + 
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "black")) +
  labs(x = "Hour",
       y = "Location",
       fill = "Msg. Freq.")
```

```{r}
freq_calculator <- function(data, workday){
  output <- data %>%
    mutate(hour = hour(timestamp)) %>%
    select(to_num, hour, to_ext) %>%
    group_by(hour) %>%
    mutate(freq = sum(to_num)) %>%
    mutate(ext_freq_perc = round(sum(to_ext) / sum(to_num) * 100, 2)) %>%
    select(-to_num) %>%
    filter(!duplicated(hour)) %>%
    mutate(weekday = rep(workday, length(hour)))
  
  return(output)
}

friday_freq <- freq_calculator(fri_combined, "Friday")
saturday_freq <- freq_calculator(sat_combined, "Saturday")
sunday_freq <- freq_calculator(sun_combined, "Sunday")

combined_freq <- rbind(friday_freq, saturday_freq, sunday_freq)

ggplot(combined_freq, aes(x = hour, y = freq, group = weekday, color = weekday)) +
  geom_line() +
  scale_x_continuous(breaks = c(8:23)) +
  labs(x = "Hour",
       y = "Message Frequency",
       color = "Work Day", 
       title = "Message Frequency by Hour") +
  theme(plot.title = element_text(hjust = 0.5),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"))
```
